audio_device: "Scarlett 2i2 USB"
ring_buffer_size_multiplier: 16
sample_rate: 44100
seedling_signal_size: 128
gain: 10000

# endpoints
output_endpoint: ipc:///tmp/analogorium
volitia_endpoint: tcp://volitia:44440

# stft
hop_size: 4
window_size: 64

# 0 for hamming
# 1 for hann
window_function: 0
